name: key_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cryptography: ^2.9.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.3.1
  test: ^1.29.0
